version: $(VERSION)(build {build})
skip_tags: true
clone_depth: 1
environment:
  JAVA_HOME: C:\Program Files\Java\jdk21
  VERSION: 0.3.1.2-1.21.5
  RELEASE_TYPE: release
  MODRINTH_TOKEN:
    secure: TsbufWPo0KHWJvMF45poicdUr9g5333TCoJnOxfhD5kH7oM7zkboVn2ilHXVKdrIf8/S6GAGlUrsy2JRA/pPcFA+ela442QsFq/dzSrNuYQ= #有效期至2025-9-11
  CURSEFORGE_API_KEY:
    secure: +FY0Vsp+IhDmayrqsjt/MbDCRDB9v5hb/BhjPK1oC+yvxytK7RaSNp2cld7Z80iX #无限期有效（？
cache:
  - C:\Users\appveyor\.gradle\caches\fabric-loom
  - C:\Users\appveyor\.gradle\caches\modules-2
build_script:
  - cmd: >-
      gradlew build --no-daemon
      
      gradlew curseforge --no-daemon
      
      gradlew modrinth --no-daemon
      
      gradlew modrinthSyncBody --no-daemon
artifacts:
  - path: .\build\libs\UltimateScaler-$(VERSION).jar
    name: UltimateScaler-$(VERSION).jar
  - path: .\build\libs\UltimateScaler-$(VERSION)-sources.jar
    name: UltimateScaler-$(VERSION)-sources.jar
deploy:
  - provider: GitHub
    tag: v$(VERSION)
    release: $(VERSION)
    description: '## 0.3.1 - 2025-8-11\n\n### 新特性 | New Features\n\n- 新增了两条常见问题。 | Added two frequently asked questions.\n\n### 改进 | Improvements\n\n- 创建了多个分支，用于支持不同版本的Minecraft。 | Created multiple branches to support different versions of Minecraft.\n- 移除了不必要的版本校验。 | Removed unnecessary version validation.\n- 替换了`README.md`中的一个徽章。 | Replaced one badge in `README.md`.\n- 升级了Gradle版本。 | Upgraded Gradle version.\n- 升级了Fabric Loader版本。 | Upgraded Fabric Loader version.\n- 整理了语言文件。 | Organized language files.\n- 为大多数分支启用了Minotaur和CurseGradle支持。 | Enabled Minotaur and CurseGradle support for most branches.\n\n## 0.3.1.1 - 2025-8-11\n\n### 漏洞修复 | Bug Fixes\n\n- 修复了某些平台上更新日志乱码的问题。 | Fixed a bug where the update log was garbled on some platforms.\n- 用`-`代替版本号中的`+`符号。 | Replaced the `+` sign in the version number with `-`.\n\n## 0.3.1.2 - 2025-8-11\n\n### 漏洞修复 | Bug Fixes\n\n- 再次尝试修复更新日志乱码的问题。 | Re-attempt to fix the update log garbled issue.\n- 将0.3.1.1的更新日志移入`BRANCH.Changelog.md`。 | Move the update log of 0.3.1.1 to `BRANCH.Changelog.md`.'
    auth_token:
      secure: MuYLGwuMDMlX3bB/PQL+ww4cs9Mmc2Nb0I2L4Ps2+GASo/K26MEUbFY1UVIgS2HR #有效期至2025-9-8
    artifact: UltimateScaler-$(VERSION).jar
    draft: false
    prerelease: false
