version: $(VERSION)(build {build})
skip_tags: true
clone_depth: 1
environment:
  JAVA_HOME: C:\Program Files\Java\jdk21
  VERSION: 0.3.2-1.21
  RELEASE_TYPE: release
  MODRINTH_TOKEN:
    secure: TsbufWPo0KHWJvMF45poicdUr9g5333TCoJnOxfhD5kH7oM7zkboVn2ilHXVKdrIf8/S6GAGlUrsy2JRA/pPcFA+ela442QsFq/dzSrNuYQ= #有效期至2025-9-11
  CURSEFORGE_API_KEY:
    secure: +FY0Vsp+IhDmayrqsjt/MbDCRDB9v5hb/BhjPK1oC+yvxytK7RaSNp2cld7Z80iX #无限期有效（？
cache:
  - C:\Users\appveyor\.gradle\caches\fabric-loom
  - C:\Users\appveyor\.gradle\caches\modules-2
build_script:
  - cmd: >-
      gradlew build --no-daemon
      
      gradlew curseforge --no-daemon
      
      gradlew modrinth --no-daemon
      
      gradlew modrinthSyncBody --no-daemon
artifacts:
  - path: .\build\libs\UltimateScaler-$(VERSION).jar
    name: UltimateScaler-$(VERSION).jar
  - path: .\build\libs\UltimateScaler-$(VERSION)-sources.jar
    name: UltimateScaler-$(VERSION)-sources.jar
deploy:
  - provider: GitHub
    tag: v$(VERSION)
    release: $(VERSION)
    description: '## 0.3.2 - 2025-8-13\n\n### 改进 | Improvements\n\n- 由于使用了新的版本管理策略和兼容代码，此分支向下兼容到1.21，并撤销了其他分支。 | This branch is now compatible down to 1.21, and all other branches have been cancelled.\n- 现在使用`@Inject`注解而非`@Overwrite`注解来修改`maintainPrecision`方法。 | Now using `@Inject` annotation instead of `@Overwrite` annotation to modify `maintainPrecision` method.\n\n### 漏洞修复 | Bug Fixes\n\n- 修复了“扩展数据包字面量取值范围”无法扩展数值下限的问题。 | Fixed that the "Extend the literal value range of datapacks" option could not extend the lower limit of the value.\n- 修复了上传到CurseForge的版本无法正常运行的问题。 | Fixed that the uploaded version to CurseForge could not run properly.'
    auth_token:
      secure: MuYLGwuMDMlX3bB/PQL+ww4cs9Mmc2Nb0I2L4Ps2+GASo/K26MEUbFY1UVIgS2HR #有效期至2025-9-8
    artifact: UltimateScaler-$(VERSION).jar
    draft: false
    prerelease: false
